// Copyright 2023 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_BUILTINS_UKERNEL_ARCH_RISCV_64_UNPACK_RISCV_64_INTERNAL_H_
#define IREE_BUILTINS_UKERNEL_ARCH_RISCV_64_UNPACK_RISCV_64_INTERNAL_H_

#include "iree/builtins/ukernel/unpack_internal.h"

IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x1_x8_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x4_x8_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x1_x32_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x8_x8_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x1_x32_riscv_64_transpose)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x1_x8_riscv_64_transpose)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x4_x8_riscv_64_transpose)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x8_x8_riscv_64_transpose)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_8x8_x32_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_generic_riscv_64_direct)
IREE_UK_UNPACK_TILE_FUNC_DECL(iree_uk_unpack_tile_generic_riscv_64_transpose)

#endif  // IREE_BUILTINS_UKERNEL_ARCH_RISCV_64_UNPACK_RISCV_64_INTERNAL_H_
